import type { Property } from './types';

export const properties: Property[] = [
  {
    id: '1',
    serial_no: 'P-1250',
    auto_title: '5 Marla House in Harbanspura',
    owner_number: '+92 300 1234567',
    city: 'Lahore',
    area: 'Harbanspura',
    address: '123-B, Canal Road, Harbanspura, Lahore',
    property_type: 'House',
    size_value: 5,
    size_unit: 'Marla',
    demand_amount: 90,
    demand_unit: 'Lacs',
    status: 'Available',
    is_recorded: true,
    created_at: '2024-05-20T10:00:00Z',
    created_by: 'user_1',
  },
  {
    id: '2',
    serial_no: 'P-1251',
    auto_title: '10 Marla Plot in DHA Phase 6',
    owner_number: '+92 321 7654321',
    city: 'Lahore',
    area: 'DHA Phase 6',
    address: 'Plot 45, Sector D, DHA Phase 6, Lahore',
    property_type: 'Plot',
    size_value: 10,
    size_unit: 'Marla',
    demand_amount: 2.5,
    demand_unit: 'Crore',
    status: 'Available',
    is_recorded: false,
    created_at: '2024-05-19T14:30:00Z',
    created_by: 'user_2',
  },
  {
    id: '3',
    serial_no: 'P-1252',
    auto_title: '2 Bedroom Flat in Gulberg',
    owner_number: '+92 333 1122334',
    city: 'Lahore',
    area: 'Gulberg',
    address: 'Apt 5A, Paradise Heights, Gulberg III, Lahore',
    property_type: 'Flat',
    size_value: 1200,
    size_unit: 'SqFt',
    demand_amount: 1.2,
    demand_unit: 'Crore',
    status: 'Sold',
    is_recorded: true,
    created_at: '2024-05-18T11:00:00Z',
    created_by: 'user_1',
  },
  {
    id: '4',
    serial_no: 'P-1253',
    auto_title: '1 Kanal Commercial Plot in Johar Town',
    owner_number: '+92 312 9876543',
    city: 'Lahore',
    area: 'Johar Town',
    address: 'Commercial Plot 8, Block G, Johar Town, Lahore',
    property_type: 'Commercial',
    size_value: 1,
    size_unit: 'Kanal',
    demand_amount: 15,
    demand_unit: 'Crore',
    status: 'Reserved',
    is_recorded: false,
    created_at: '2024-05-17T09:00:00Z',
    created_by: 'user_3',
  },
  {
    id: '5',
    serial_no: 'P-1254',
    auto_title: '8 Marla House in Bahria Town',
    owner_number: '+92 345 5566778',
    city: 'Lahore',
    area: 'Bahria Town',
    address: 'House 786, Sector C, Bahria Town, Lahore',
    property_type: 'House',
    size_value: 8,
    size_unit: 'Marla',
    demand_amount: 1.8,
    demand_unit: 'Crore',
    status: 'Available',
    is_recorded: false,
    created_at: '2024-05-21T16:00:00Z',
    created_by: 'user_2',
  },
];
